org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Erforderlich für das externe JetBrains Kotlin-Plugin mit AGP 9
android.builtInKotlin=false
android.newDsl=false

# Warnungen unterdrücken & Sync-Performance optimieren
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
